# netlify.toml

[build]
  # Perintah build Vite (otomatis tahu tentang src)
  command = "npm run build"
  # Direktori output hasil build
  publish = "dist"

[functions]
  # Direktori kode functions
  directory = "netlify/functions/"
  node_bundler = "esbuild"

# (Opsional) Redirect untuk API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
